### ISSUE TITLE
Unable to withdraw SLP or claim rewards from System 11

### ISSUE THREAD

**Issue by aidonaks** [0xNODES/community#14]
Every since the update on Nov 19, I am unable to withdraw the SLP I deposited into System 11 or claim BIOS rewards.

Both of those give the error 

This has been brought up *many times* in the official channels by multiple people and Mafaku even commented on it in the Discord, but apparently neither Owl nor Swanson were somehow unaware.

I am therefore posting it here because Owl asked me to.

![image](https://user-images.githubusercontent.com/29076196/142968328-6e79ee85-acb7-496b-b4ed-0a0b7045a7a7.png)

**Comment by jensonb** [comment]
Hi @aidonaks , thanks so much for sending in this report. We were able to diagnose this issue and released the fix for it on Nov 25th. The issue was related to our system updates from Nov 19 causing unexpected gas estimation issues to occur while determining transaction gas fees. If you are still experiencing that same issue, you may have to do a hard refresh in your web browser of the system11 dapp to make sure that you have that recent update loaded. If you are still having problems at that point, 

That being said, please hold off for a minute on claiming the BIOS rewards. There is a separate issue there that we are currently working on, and expect to have a fix for that released within the next 72 hours. I will give you another update on here after that fix has been released.

Thank you again for your patience and for submitting this bug report, they are extremely valuable in helping our awareness of these issues. I see you have reported several other issues on here as well. I've been assigned to manage the community feedback on here now, so I expect we will be talking some more in the future :)

You can expect an update from me here on the BIOS rewards claiming within 72 hours.

**Comment by aidonaks** [comment]
Hi Jenson,

Thanks for the update. I just tried both a hard a refresh and also deleting cache but I still get the same error.

I'll wait for your next update or try again once 72 hrs have elapsed.

**Comment by jensonb** [comment]
hi @aidonaks,

We have rolled out a fix just now to enable you to claim your rewards. We are still working on a fix for the `CLAIM.ALL_ASSETS` function, so in the mean time we have updated the dapp to allow users to `CLAIM.BIOS_REWARDS` and `CLAIM.ETH_REWARDS`:

![image](https://user-images.githubusercontent.com/19617447/143803805-d093d48b-9918-4726-bb83-6397dbc2ee1b.png)

This should allow you to claim any rewards that you would like. You are of course welcome to continue to wait until we fix and restore the `CLAIM.ALL_ASSETS` function if you prefer, although I cannot give you an exact timeline on when that issue will be resolved.

Just to make sure we are all on the same page, when you claim your rewards, the rewards will be sent from the system to your wallet. While the rewards are unclaimed, the rewards emitter already includes them in its calculation of rewards distributions. In other words, claiming your rewards will reduce the amount of tokens you have in the system and thus slow your rewards accrual unless you deposit them back into the Kernel. Just want to make sure you understand the functionality of the system right there, since better documentation is another feature that we are still working on.

If you decide to claim your rewards or withdraw some assets, we would love to hear a confirmation that the fixes worked for you.

Thanks again for using 0xNODES and submitting the bug report!

**Comment by aidonaks** [comment]
I tried the "claim bios rewards" button and now it does give me the Metamask prompt!

I didn't try completing the process yet but there's no reason why it won't work.

Thanks for your help.

**Comment by aidonaks** [comment]
So do I get a reward for this? 😉

![image](https://user-images.githubusercontent.com/29076196/143924593-17536545-f413-4a83-b275-7b6f61738b40.png)
